### ISSUE TITLE
Compilation error on nightly + cel 0.11 "(dyn Vocabulary + 'static)` cannot be sent between threads safely"

### ISSUE THREAD

**Issue by bickfordb** [cel-rust/cel-rust#188]
When I add cel to a small example project it works fine.  When I add it to my larger project, I encounter the following error. 

```   Compiling cel v0.11.0
error[E0277]: `(dyn Vocabulary + 'static)` cannot be sent between threads safely
   --> /Users/bran/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cel-0.11.0/src/parser/gen/cellexer.rs:194:1
    |
194 | / lazy_static! {
195 | |     static ref _shared_context_cache: Arc<PredictionContextCache> =
196 | |         Arc::new(PredictionContextCache::new());
197 | |     static ref VOCABULARY: Box<dyn Vocabulary> = Box::new(VocabularyImpl::new(
...   |
201 | |     ));
202 | | }
    | |_^ `(dyn Vocabulary + 'static)` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `(dyn Vocabulary + 'static)`
    = note: required for `Unique<(dyn Vocabulary + 'static)>` to implement `Send`
note: required because it appears within the type `Box<(dyn Vocabulary + 'static)>`
   --> /Users/bran/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:231:12
    |
231 | pub struct Box<
    |            ^^^
    = note: required for `spin::once::Once<Box<(dyn Vocabulary + 'static)>>` to implement `Sync`
note: required because it appears within the type `lazy_static::lazy::Lazy<Box<(dyn Vocabulary + 'static)>>`
   --> /Users/bran/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lazy_static-1.5.0/src/core_lazy.rs:12:12
    |
 12 | pub struct Lazy<T: Sync>(Once<T>);
    |            ^^^^
    = note: shared static variables must have a type that implements `Sync`
    = note: this error originates in the macro `__lazy_static_create` which comes from the expansion of the macro `lazy_static` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `(dyn Vocabulary + 'static)` cannot be sent between threads safely
   --> /Users/bran/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cel-0.11.0/src/parser/gen/celparser.rs:187:1
    |
187 | / lazy_static! {
188 | |     static ref _shared_context_cache: Arc<PredictionContextCache> =
189 | |         Arc::new(PredictionContextCache::new());
190 | |     static ref VOCABULARY: Box<dyn Vocabulary> = Box::new(VocabularyImpl::new(
...   |
194 | |     ));
195 | | }
    | |_^ `(dyn Vocabulary + 'static)` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `(dyn Vocabulary + 'static)`
    = note: required for `Unique<(dyn Vocabulary + 'static)>` to implement `Send`
note: required because it appears within the type `Box<(dyn Vocabulary + 'static)>`
   --> /Users/bran/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:231:12
    |
231 | pub struct Box<
    |            ^^^
    = note: required for `spin::once::Once<Box<(dyn Vocabulary + 'static)>>` to implement `Sync`
note: required because it appears within the type `lazy_static::lazy::Lazy<Box<(dyn Vocabulary + 'static)>>`
   --> /Users/bran/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lazy_static-1.5.0/src/core_lazy.rs:12:12
    |
 12 | pub struct Lazy<T: Sync>(Once<T>);
    |            ^^^^
    = note: shared static variables must have a type that implements `Sync`
    = note: this error originates in the macro `__lazy_static_create` which comes from the expansion of the macro `lazy_static` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `cel` (lib) due to 2 previous errors
```

Any idea why?

**Comment by torbensen** [comment]
I’m hitting the same error in a larger workspace project.

- Error
  ```
  error[E0277]: `(dyn Vocabulary + 'static)` cannot be sent between threads safely
     --> ~/.cargo/registry/.../cel-parser-0.10.1/src/gen/cellexer.rs:194:1
      |
  194 | lazy_static! {
      | ^ `(dyn Vocabulary + 'static)` cannot be sent between threads safely
      = help: the trait `Send` is not implemented for `(dyn Vocabulary + 'static)`
      = note: required for `spin::once::Once<Box<(dyn Vocabulary + 'static)>>` to implement `Sync`
  ...
  ```
  (The same at `celparser.rs`.) This matches what’s reported here: [cel-rust/cel-rust#188](https://github.com/cel-rust/cel-rust/issues/188#issue-3394857535).

- Environment
  - OS: macOS (arm64)
  - Toolchain: stable (aarch64-apple-darwin)
  - Workspace: multi-crate (building a server crate in a larger workspace)

- Versions
  - cel-interpreter = "0.10"
  - This pulls in cel-parser = "0.10.1" (from crates.io)
  - I attempted to override cel-parser to 0.11 via `[patch.crates-io]`, but 0.11 is not published on crates.io, so the patch fails to resolve.

- Repro (simplified)
  1) Add `cel-interpreter = "0.10"` to Cargo.toml.
  2) `cargo build` in a multi-crate workspace.
  3) Build fails with E0277 shown above.

- What I tried
  - Workspace-level `[patch.crates-io]` to point `cel-parser` to 0.11: not available on crates.io.
  - Considered swapping to `rscel` or `cel-cxx` as a temporary workaround, but I’d prefer to stay on the current stack if possible.

- Question
  - Is this considered a bug in the generated parser (static `lazy_static!` holding a non-`Sync` trait object), or is there a deliberate trade-off here?
  - Is there a recommended short-term workaround (feature flag, config, or safe init pattern)?
  - Any plan to publish a crates.io release that avoids putting a non-`Sync` trait object in a global `lazy_static!` (e.g., `Arc<dyn Vocabulary + Send + Sync>`, or switching to a `once_cell` + concrete type)?

Thanks a lot for any guidance!

**Comment by clarkmcc** [comment]
@alexsnaps any thoughts on this before I dive in?

**Comment by clarkmcc** [comment]
Okay, sorry for the delay on this. I finally had a moment to sit down and look at this. The crates were consolidated to a single `cel` crate. See [getting started](https://github.com/cel-rust/cel-rust?tab=readme-ov-file#getting-started) and the [examples](https://github.com/cel-rust/cel-rust/blob/master/example/src/simple.rs) to see how to use the new crate.

I just `cargo clean` ran the whole test suite and everything should be working on the new crate. Please let me know if you still have issues after that.

**Comment by bickfordb** [comment]
Did a `cargo clean` and still getting the error.  I have cel.version set to "0.11.1" 

```
➜  ~ rustc --version
rustc 1.91.0-nightly (9c27f27ea 2025-09-08)
➜  ~ cargo version
cargo 1.91.0-nightly (761c4658d 2025-09-04)
➜  ~
```

**Comment by clarkmcc** [comment]
Hm... must be something to do with nightly. Thanks for sending your versions. I'll download and run some tests on my side.

**Comment by clarkmcc** [comment]
@bickfordb I think I'm going to need a reproduction from you. I can't reproduce with the `cel` test suite.

```
$ rustc --version
rustc 1.91.0-nightly (9c27f27ea 2025-09-08)

$ cargo clean
$ cargo test
test result: ok. 73 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s
test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.27s
```

Based on the error, it sounds like you're trying to send something cel-related between threads. If you could share what you're trying to do, I might be able to point you in the right direction. For an example of using cel in multi-threaded contexts see the [threading example](https://github.com/cel-rust/cel-rust/blob/master/example/src/threads.rs).

**Comment by bickfordb** [comment]
Thanks for looking into this.  I'll try to create a simple reproduction

**Comment by torbensen** [comment]
I have already opened an issue and a PR for antlr4rust:
https://github.com/antlr4rust/antlr4/issues/10

While waiting for it to be merged, you can use the following temporary workaround in your Cargo.toml:
```
[patch.crates-io]
antlr4rust = { git = "https://github.com/chainstream-io/antlr4.git", rev = "b4cc9dfa9b662769a18668aa75c8a6fb23eedf50" }
```

**Comment by alexsnaps** [comment]
@torbensen this is great. 
I'm sadly away from a computer until the end of next week. But it'll be my priority to sort this all out then. 
Thanks for the PR and sorry about the delay

**Comment by alexsnaps** [comment]
It's merged, but I can't release for another week. Pointing to main would work tho until then

**Comment by torbensen** [comment]
> It's merged, but I can't release for another week. Pointing to main would work tho until then

@bickfordb  You also can temporarily use:
```
[patch.crates-io]
antlr4rust = { git = "https://github.com/antlr4rust/antlr4.git", branch = "rust-target" }
```

**Comment by alexsnaps** [comment]
It'd be great to hear back if this fixes it all for you and no further issue exists

**Comment by alexsnaps** [comment]
Released [`antlr4rust v0.3.0-rc1`](https://crates.io/crates/antlr4rust/0.3.0-rc1) and updated dependency _explicitly_ #189

**Comment by clarkmcc** [comment]
Release cel-0.11.2 which incorporates this change.

**Comment by alexsnaps** [comment]
I've been looking into possible other issues with the antlr4rust library... 
There might be "other" issues. It would be really nice to get a reproducible test case still. 
If I'm getting this right there is a little bit of a broken promise wrt thread-safety and the parser being generated (which is `Send`, but _not_ `Sync`). I'm fairly sure it shouldn't be `Sync` ever... but I'm investigating this. 

Now, while I still need to get my head around it, but let's be clear that it is no issue for this library, as a `cel::parser::Parser` isn't meant to be thread safe. Tho it may look from a type system perspective that it may, you wouldn't be able to reuse it (whether across threads or even a single one), given `parse` consuming `self`, which is by design:

```rust
pub fn parse(mut self, source: &str) -> Result<IdedExpr, ParseErrors> 
```

So `Send` is "fine", but not `Sync`, yet it is... until one thread probably locks it to get `mut` access and then consumes it.

**Comment by alexsnaps** [comment]
I think this can safely closed now.
